services:

  db:
    image: example/postgres
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  java:
    image: example/java
    build: 
      context: java
    restart: always
    ports:
      - "127.0.0.1:8081:8080"

  typescript:
    image: example/typescript
    build:
      context: 
        ./typescript
      args:
        - APP_ENV=production
    restart: always
    ports:
      - "127.0.0.1:8082:5050"
